### ISSUE TITLE
generate ground truth verification data

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ml#11]
Ground truth data can be easily generated using the [Matlab Automated Driving System Toolbox](https://de.mathworks.com/videos/introduction-to-automated-driving-system-toolbox-1497301373787.html).

# ToDo List
- [x] evaluate Matlab Automated Driving System Toolbox
- [x] find optimal workflow
- [x] write down workflow
- [x] crop image to some region? -> no
- [x] script converting the matlab file to .csv
- [x] store everything in a separate folder in drive_ml->sign-recoginition->utilities
