### ISSUE TITLE
Deep Reinforcement/Imitation Learning

### ISSUE THREAD

**Issue by xXBasti** [tum-phoenix/drive_ml#21]
# Objective: Train a network to control the car 

Deep Reinforcement learning is a promising approach for autonomous robots and has been utilized in Autonomus Driving. This would be end-to-end trainable though. 

## Network architecture (Agent)
- TBD
- [Imitation Learning](https://arxiv.org/abs/1709.07174): Alternative approach, learn the driving strategy end-to-end from recorded data

## Simulation Environment:
- [Gazebo Simulation](https://github.com/tum-phoenix/drive_gazebo_sim), realism could be higher, but integrates all of our ROS inputs directly, so directly reusable in the real world. LIDAR and cameras as well as the side switch are simulated.
- Other publicly available simulators with custom environments: [AirSim](https://github.com/microsoft/AirSim) or [Carla](http://carla.org/)

# Constraints:
* The network has to run at least at 25FPS on our on-board hardware (A [Jetson TX2](https://developer.nvidia.com/embedded/buy/jetson-tx2) \)
* This also includes communication with the ROS core running on the main Intel NUC board

# Tasks:
- [ ] Setup Gazebo simulation
- [ ] Research Deep Reinforcement Learning.
- [ ] Try out different approaches in the Simulation
- [ ] Benchmark on the car to measure performance and detect problems

# Resources:
https://github.com/simoninithomas/Deep_reinforcement_learning_Course
